import React, { useState, useEffect } from 'react';
import { Target, Lightbulb, Loader2 } from 'lucide-react';

const SummaryPanel: React.FC = () => {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const response = await fetch('http://localhost:5000/summary');
        if (response.ok) {
          const data = await response.json();
          setSummary(data.summary);
        }
      } catch (err) {
        console.error("Failed to fetch summary", err);
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, []);

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center space-y-4 text-gray-500">
        <Loader2 className="animate-spin" size={32} />
        <p className="font-medium">Generating smart summary...</p>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto px-6 py-8 space-y-8 custom-scrollbar bg-gray-50/50">
      <div className="space-y-2">
        <div className="flex items-center space-x-2 text-blue-600 font-bold uppercase tracking-wider text-xs">
          <SparkleIcon className="w-4 h-4" />
          <span>AI Generated Summary</span>
        </div>
        <h2 className="text-2xl font-extrabold text-gray-900 leading-tight">
          Document Overview
        </h2>
      </div>

      <div className="grid gap-6">
        <SummaryCard 
          icon={<Target className="text-blue-600" size={20} />}
          title="Analysis"
          content={summary || "No summary available for this document."}
        />

        <div className="bg-blue-50/50 p-6 rounded-2xl border border-blue-100 flex items-start space-x-4">
           <Lightbulb className="text-blue-600 shrink-0 mt-1" size={20} />
           <p className="text-sm font-medium text-gray-700 leading-relaxed">
             This summary is automatically generated by analyzing the first several pages of your document to provide a quick context-aware overview.
           </p>
        </div>
      </div>

      <div className="pt-8 text-center">
        <p className="text-xs text-gray-400 font-medium">
          Powered by Llama 3.3 • Context-aware RAG
        </p>
      </div>
    </div>
  );
};

const SummaryCard = ({ icon, title, content, bgColor = "bg-white" }: { icon: React.ReactNode, title: string, content: string, bgColor?: string }) => (
  <div className={`${bgColor} p-6 rounded-2xl premium-shadow border border-gray-100 space-y-2`}>
    <div className="flex items-center space-x-2 mb-1">
      {icon}
      <h3 className="font-bold text-gray-900">{title}</h3>
    </div>
    <p className="text-sm font-medium text-gray-700 leading-relaxed">
      {content}
    </p>
  </div>
);

const SparkleIcon = (props: any) => (
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M12 3L14.5 9L21 11.5L14.5 14L12 21L9.5 14L3 11.5L9.5 9L12 3Z" fill="currentColor"/>
  </svg>
);

export default SummaryPanel;
